### ISSUE TITLE
kan ikke uploade rawfile 

### ISSUE THREAD

**Issue by TanyaPS** [Kortforsyningen/GORM#1]
Når man uploader via RINEX distribution, så kan man ikke vælge raw som en filetype

**Comment by sjmoller** [comment]
Det er fixet nu. Installer patch med:
Login på gpsftp og gør følgende:
$ sudo su -
# su - gpsuser -c 'git pull'
# ~gpsuser/setup/install.sh
# systemctl restart gpspickup jobengine

**Comment by kbevers** [comment]
Og det var i 36a005f det blev fikset.

**Comment by kbevers** [comment]
Nu også installeret på GPSFTP5
