### ISSUE TITLE
Header korrektion i dagsfil, ved ændring af Antenne, Modtager, Firmware ell. lign.

### ISSUE THREAD

**Issue by casperjepsen** [Kortforsyningen/GORM#11]
Hvis der ændres noget på Siten, (modtager firmware, antenne, Modtager ell noget andet der står i Headeren, Så SKAL den seneste inddatering være den der står i headeren på Dagfilen. Dvs hvis Henrik Skifter fw kl 15, så skal headeren være på dagfilen den seneste entry.

**Comment by sjmoller** [comment]
Denne pull request [patch](https://github.com/Kortforsyningen/GORM/commit/fe9597f666f71bd8f62e5d8955e5a5f065b884db) retter dette til at anvende header fra og med den dag rettelsen blev udført.

**Comment by sjmoller** [comment]
Installeret på gpsftp5
