### ISSUE TITLE
Koordinater i Admin modul skal også være tidsstyret

### ISSUE THREAD

**Issue by casperjepsen** [Kortforsyningen/GORM#12]
Når der ændres en koordinat på stationen skal den (som nu) indtastes i "Edit Site" i ADM modulet. Dette felt skal gøres tidsstyret på samme vis som Antenne, Modtager og Firmware.

**Comment by kbevers** [comment]
Se https://github.com/Kortforsyningen/GORM/issues/9. Tilføj evt. yderligere info i det eksisterende issue.
