### ISSUE TITLE
Nav filer på ftp.kortforsyningen skal samles til 1 fil

### ISSUE THREAD

**Issue by casperjepsen** [Kortforsyningen/GORM#13]
Som det er nu er der nogle af stationerne der har separate Nav filer for GPS og Glonass og ... De skal samles til éen fil (Mixed Navigation File)

**Comment by sjmoller** [comment]
Denne feature er installeret nu.

**Comment by kbevers** [comment]
@sjmoller super. Jeg går ud fra at det er i https://github.com/Kortforsyningen/GORM/commit/608e298fbba541d78a21681b96012fa160a06822 det er ændret?

Så vidt jeg kan se mangler vi stadig at merge nav-filer der er produceret før ca. 1 februar. I hvert fald for udvalgte stationer. Har vi en nem måde at gøre det på?

**Comment by sjmoller** [comment]
Problemet er nav filerne også ligger på ftp.kortforsyningen.dk, og de slettes ikke automatisk når man (gen)uploader RINEX3 til den.
Den klart nemmeste måde er et reprocessere dagene. Og det skal vi alligevel for at få de helt rigtige RINEX headere. Inden man reprocessrer, så skal filerne slettes fra ftp.kortforsunignen.dk for at komme af med de "forkerke" nav filer.

**Comment by kbevers** [comment]
Tak. Vi kom frem til samme konklusion tidligere i dag. Tanya har sat nogle dage til reprocesseringen for at se hvordan det går.
