### ISSUE TITLE
Håndter MDB filer fra Leica

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/GORM#14]
# Baggrund
Vi sender lige nu RINEX3 filer direkte fra station til gpsftp5 OG vi sender også Leica rådata MDB filer til gpsftp4. Det skal ensrettes sådan at data kun sendes een gang. Da vi skal processere RINEX2 filer vil det være mest praktisk hvis stationen sender rådatafilen i Leicas MDB format. MDB omdannes i dag til RINEX2 uden problemer, men det samme kan vi ikke med RINEX3.
 
# Potentiel løsning
Leica har noget software de skriver kan lave MDB til RINEX3 på Linux. Desværre softwaren er dateret 20.12.2018 og vil formentlig ikke kunne lave RINEX 3.04. 

Start med at undersøge hvad det kan og ikke kan. Hvilke output kan Leicas program give? Både RINEX2 og RINEX3? Og i så fald hvilke versioner af standarden. 

Når det er afklaret kan vi se på hvordan det bedst implementeres i vores software.

**Comment by TanyaPS** [comment]
Henrik og jeg har kigget på Leicas konverterings software: 
Den konverterer MDB til RINEX v3.02 og navngiver efter RINEX2 regler. Umiddelbart er der ikke muligheder for at få andet output.

**Comment by casperjepsen** [comment]
Jeg har været i dialog med Leica, der ikke umiddelbart kan forstå hvorfor deres windows program ikke er godt nok!, de kan heller ikke forstå hvorfor Rinex version 3.02 ikke er fint nok. 
Jeg holder dem til ílden.

**Comment by kbevers** [comment]
Tak! Prøv evt at se om du kan blive henvist til nogle af deres udviklere. De er sikkert nemmere at få til at se fidusen i det.

**Comment by sjmoller** [comment]
:-) Typisk for Windows udviklere...
Mon ikke det hjælper lidt at henvise til konkurrentens "sbf2rin" eller
lignende.

**Comment by casperjepsen** [comment]
Er der slet ikke nogen af jer "linux nørder" der har aktier i Bill Gates virksomhed? :-)

**Comment by sjmoller** [comment]
Micro$oft er nu ikke så dum en aktie at have i sin pensionsopsparing...

Men det er nu ikke så stort et problem at Leica stationer sender i 3.02
format. Gpsftp5 opgraderer formatet til 3.04 når de processeres (gøres i
splice processen). Problemet er nok snarre vi så er nødt til at uploade
både MDB data og RINEX3.zip data fra Leica stationerne. Spild af
båndbredde, men så er det heller ikke værre. Det samme gælder for Trimble.

**Comment by casperjepsen** [comment]
Jeg tror desværre at vi kommer til at mangle vigtig information hvis vi "kun" beholder 3.02. En konvertering fra 3.02 til 3.04 gør jo ikke de fejl der er i 3.02 mere rigtige! Jeg er 100% enig i at vi skal undgå at sende både rinex3.0X og rådata fra modtageren, hvorfor vi også håber på at det er muligt at konvertere rådata til rinex3.04

**Comment by sjmoller** [comment]
Du har naturligvis ret dette.
Jeg må indrømme jeg har svært ved at forstå hvorfor Leica (og Trimble) ikke gør alt hvad de kan for at levere forbedringer og utilities deres kunder ønsker og har brug for. Det er vel en af de parametre man tager i betragtning når man vælger leverandør... Flexibilitet gør en forskel.

**Comment by kbevers** [comment]
Leica vil ikke spille bold i øjeblikket. Vi lukker denne og venter på at de kommer op i omdrejningerne på et senere tidspunkt.
