### ISSUE TITLE
utilsigtede hændelser når sbf2rin fejler (f.eks BUDD024d.20_) 

### ISSUE THREAD

**Issue by nho-sdfe** [Kortforsyningen/GORM#19]
Der bliver efterladt noget .rnx i saved og upload/gpsftp4/saved, når sbf2rin fejler på gpsftp5.
Det betyder at der bliver sendt ftp .rnx filer til gpsftp4.
[sbf2rin_fejl.txt](https://github.com/Kortforsyningen/GORM/files/4149219/sbf2rin_fejl.txt)

**Comment by sjmoller** [comment]
Jeg forstår ikke helt hvorfor den fejler og slet ikke hvorfor der efterlades filer i /data/ftp.
Nu forsøger jeg at kopiere rawfilen til unpackdir og kører sbf2rin i det katalog for at sikre mig at der ikke efterlades filer utilsigtede steder. Der var sådan set ikke noget galt i det jeg gjorde før, men der er åbenbart en bug i sbf2rin som nogen gange skriver filer samme sted som raw filen ligger og ikke i det nuværende katalog. Nogen gange.... langt fra ofte.
@TanyaPS og @kbevers - undskyld.. Jeg kom til at committe i master og ikke som en pull request. Jeg glemte at lave en ny branch... Det er denne commit:
[91eb9b2cbada8b0d7565fb48c8ad357c124377db](https://github.com/Kortforsyningen/GORM/commit/91eb9b2cbada8b0d7565fb48c8ad357c124377db)

**Comment by kbevers** [comment]
> @TanyaPS og @kbevers - undskyld.. Jeg kom til at committe i master og ikke som en pull request. Jeg glemte at lave en ny branch... Det er denne commit:
91eb9b2cbada8b0d7565fb48c8ad357c124377db

Jeg har sat "branch protection" op for master - så sker det ikke igen :-) Du skulle gerne blive afvist hvis du prøver at pushe direkte til master.

**Comment by kbevers** [comment]
> men der er åbenbart en bug i sbf2rin som nogen gange skriver filer samme sted som raw filen ligger og ikke i det nuværende katalog. Nogen gange.... langt fra ofte.

Den bør vi i øvrigt rapportere til Septentrio, så de kan få fikset problemet. Kan du reproducere fejlen, Søren?

**Comment by sjmoller** [comment]
Det er netop det. Jeg har kørt sbf2rin mindst 1000 gange og aldrig set den gøre det - heller ikke under vildt høj belastning. Vi man kan jo se at den gør det engang imellem på gpsftp5. Med den senste rettelse vil jeg være meget overrasket hvis vi ser dette igen. Der skiftes katalog i samme shell som programmet kører, og samtidigt med det ligger raw filen i samme katalog som der pakkes ud i. Så hvis der ligger filer andre steder nu, så er det noget helt andet der er galt.

sbf2rin burde have en option hvor man kan angive hvilket katalog filerne skal genereres i. Men det har den ikke.
