### ISSUE TITLE
Kontroller ant. højde og kooordinater på alle stationer.

### ISSUE THREAD

**Issue by casperjepsen** [Kortforsyningen/GORM#2]
Jeg har observeret at flere af stationerne havde en forkert position i rinex headeren. De skal kontrolleres i henhold til sitelog og Valdemar DB.

**Comment by kbevers** [comment]
Dette er formentligt en opgave der kan løses med et script der holder data fra site-log op mod data i RINEX headeren. Tænk over om det kan lade sig gøre at skrive sådan et script.

**Comment by sjmoller** [comment]
Koordineterne og antenne højden kan konfigureres i admin interfacet (under site og under Edit Antennas).
Formatet for koordinater er x,y,z - f.eks. 3513648.5314,778955.7471,5248203.7038  (ingen mellemrum, og punktum som decimal tegn).
Formatet for antennehøjde Delta (H,E,N) er det samme, f.eks.  0.19464,0,0
Er det angivet der, så anvendes det i RINEX headeren uanset hvad stationen har skrevet.

**Comment by kbevers** [comment]
> Nok en god ide at kontrollere sitelogs op mod de officielle koordinater i refgeo.

Ja, det er det også, omend det er lidt mere bøvlet at lave et script der gør det (i hvert fald i øjeblikket, fremtiden er lys hvad det angår). På sigt skal vi have en form for integration mellem GNSS-systemerne og fikspunktsregisteret. Det er jo nærliggende at koordinater der indføres i RINEX-headere snuppes direkte fra fikspunktsdatabasen.

**Comment by sjmoller** [comment]
I skal være opmærksom på at efter den seneste release af scriptet, så er alle positioner konfigureret i databasen væk. De skal konfigureres i den nye dato baserede tabel (ligesom antenner og modtagere) for hver site. Hvis der ikke er nogen positioner for en given site, så anvendes positionen angivet af siten selv.

**Comment by kbevers** [comment]
> I skal være opmærksom på at efter den seneste release af scriptet, så er alle positioner konfigureret i databasen væk. De skal konfigureres i den nye dato baserede tabel (ligesom antenner og modtagere) for hver site. Hvis der ikke er nogen positioner for en given site, så anvendes positionen angivet af siten selv.

Jeg skal lige forstå præcis hvad det betyder. Vi har endnu ikke installeret den seneste version. Altså den fra #18. Hvis vi opdaterer koden ud fra den vejledning du har skrevet i det tilhørende pull request, tømmes databasen så for indhold? Henrik og Tanya sidder netop og arbejder på at opdatere databasen i forbindelse med dette issue, og vi skulle nødigt ende i en situation hvor deres arbejde er forgæves.

**Comment by TanyaPS** [comment]
de positioner vi lige har sat ind er sat ind i den dato baserede tabel (altså edit sit ->edit positions i admin interfacet). Det er vel der de bliver gemt nu

**Comment by sjmoller** [comment]
For at være helt præcis. Den version som kører nu har positioner i sin egen tabel. Så Edit Site -> Edit Positions er de(n) gældende position(er) for en given site. Database schemaet er naturligvis opgraderet til at kunne håndtere dette.
Den version som ligger og venter er den hvor scriptene køres fra hvor de er klonet til (paralle instanser) og en fix til sbf2rin problemet.

**Comment by kbevers** [comment]
Tak, så lyder det som om der er styr på det hele :-)

**Comment by kbevers** [comment]
@TanyaPS @nho-sdfe har I ikke gjort det her for længe siden? Altså manuelt, jeg er med på at scriptet til det ikke er helt på plads endnu.

**Comment by TanyaPS** [comment]
jo det er blevet gjort manuelt
