### ISSUE TITLE
bug i edit antennas i admin interface 

### ISSUE THREAD

**Issue by TanyaPS** [Kortforsyningen/GORM#20]
Edit antennas i admin interface kan ikke håndtere negative antenne højder. En skal f.eks være 0.1731,-0.0030,0

**Comment by sjmoller** [comment]
@TanyaPS 
Hint: Se hvordan positions data behandles i editpositions() og implementer den samme regex for antdelta i editantennas()

**Comment by sjmoller** [comment]
Denne er fixet, ikke?

**Comment by kbevers** [comment]
Jeg tror den er fikset her https://github.com/Kortforsyningen/GORM/commit/7246627a2085f1f37822a77a922b57d25002469e ?

**Comment by TanyaPS** [comment]
jo det er den
