### ISSUE TITLE
Kan ikke oprette nye stationer på gpsftp5

### ISSUE THREAD

**Issue by nho-sdfe** [Kortforsyningen/GORM#25]
Når man har udfyldt New Site og trykker save, kvitteres der med "Site xxx created".
Men stationsnavnet optræder ikke på Edit sites listen efterfølgende.
![image](https://user-images.githubusercontent.com/55193081/76952019-be36ae00-690c-11ea-90b9-bb759265bc6d.png)
![image](https://user-images.githubusercontent.com/55193081/76952066-cee72400-690c-11ea-8b5e-e142fcdcb6cf.png)

**Comment by TanyaPS** [comment]
@kbevers @sjmoller kan det være problemer med at skrive til databasen? Kan ikke umiddelbart se noget galt i scriptet. Hvordan kan jeg se i databasen for at checke?

**Comment by kbevers** [comment]
@TanyaPS du må kunne logge ind på databaseinterfacet i en browser (phpmyadmin, er det ikke det vi bruger?) og prøve manuelt at indsætte en række i en tabel. Eller måske mere sikkert, oprette en ny tabel og slette den igen. Hvis du kan det, så har du udelukket et problem.

**Comment by sjmoller** [comment]
Denne fejl er reproducerbar:

Output i /var/log(httpd/error_log:
> [Sun Mar 22 15:30:41.864328 2020] [cgi:error] [pid 65691] [client 192.168.74.3:51105] AH01215: DBD::mysql::db do failed: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 3 at /home/0.99.2/www/admin.cgi line 96., referer: https://gpsftp5.moellers.dk/prod/admin.cgi?cmd=newsite

Som man kan se, så er der en syntaxfejl i SQL kommandoen der indsætter data i databasen. Linje 96.
Jeg har rettet fejlen i 0.99.2.

**Comment by nho-sdfe** [comment]
Det var ikke helt nok...
Skal måske også rettes i http://gpsftp5.prod.sitad.dk/ og ikke kun i https://gpsftp5.moellers.dk/


[Sun Mar 22 03:19:02.400380 2020] [lbmethod_heartbeat:notice] [pid 62406] AH02282: No slotmem from mod_heartmonitor
[Sun Mar 22 03:19:02.453614 2020] [mpm_prefork:notice] [pid 62406] AH00163: Apache/2.4.6 (Red Hat Enterprise Linux) PHP/5.4.16 configured -- resuming normal operations
[Sun Mar 22 03:19:02.453633 2020] [core:notice] [pid 62406] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Mon Mar 23 08:44:59.115351 2020] [auth_basic:error] [pid 38862] [client 10.33.128.225:58339] AH01618: user Admin not found: /prod/admin.cgi
[Mon Mar 23 08:45:08.679652 2020] [auth_basic:error] [pid 38865] [client 10.33.128.225:58353] AH01618: user Admin not found: /prod/admin.cgi
[Mon Mar 23 08:54:25.587475 2020] [cgi:error] [pid 38864] [client 10.33.128.225:59063] AH01215: DBD::mysql::db do failed: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 3 at /usr/local/gorm/prod/www/admin.cgi line 96., referer: http://gpsftp5.prod.sitad.dk/prod/admin.cgi?cmd=newsite

**Comment by TanyaPS** [comment]
er der ikke bare at merge pull requested?

**Comment by kbevers** [comment]
Jo. Og så rent faktisk installere koden på serveren! Det går jeg ikke ud fra at Søren har gjort.
