### ISSUE TITLE
Måske relation til #25, rettigheder til at oprette biblioteker?

### ISSUE THREAD

**Issue by nho-sdfe** [Kortforsyningen/GORM#26]
Hej.

Selvom jeg satte SULD00DNK activ i går er det ikke gået så godt.

Filer på modtageren som er blevet ftp pushed:
 
![modtager](https://user-images.githubusercontent.com/55193081/77049858-1d59f880-69c9-11ea-9b7f-854edef967e3.jpg)

Gps (Log) som viser at der kun er foretaget noget med de 3 første filer:

Mar 18 18:23:31 GPSFTP5 gpspickup: SULD00DNK_R_20200781502_01H_01S.rnx.zip: Cannot handle sub-hour files. Manual splice needed.
Mar 18 18:23:52 GPSFTP5 gpspickup: gunzip SULD00DNK_R_20200781600_01H_01S.rnx.zip.gz
Mar 18 18:24:00 GPSFTP5 gpspickup: gunzip SULD00DNK_R_20200781700_01H_01S.rnx.zip.gz

De er efterfølgende forsvundet fra gpsftp5…

SULD00DNK biblioteket er ikke blevet oprettet i data/work/ da stationen er blevet oprettet og heller ikke ved at gøre stationen activ.
 
![work_bib](https://user-images.githubusercontent.com/55193081/77049991-55f9d200-69c9-11ea-9c31-8c7ae21df49b.jpg)

**Comment by sjmoller** [comment]
Hej.

Jeg skal se om jeg får lidt tid i dag til at se på det.
Der er nok en lille bug i admin.cgi.

/Søren

**Comment by nho-sdfe** [comment]
Hej igen.

Var vist lidt hurtig til at se efter biblioteker. ftp-problemer? 
SULD00DNK er faktisk oprettet i både /work og i /saved
Men SULD bliver ikke behandlet og det kan måske skyldes at jeg sat modtageren til at
navngive rinex filerne med long names. Det giver i hvert lidt bøvl.
![SULD-work](https://user-images.githubusercontent.com/55193081/77060240-8c8b1900-69d8-11ea-95cd-dd2132fb0230.jpg)
![TEJH-work](https://user-images.githubusercontent.com/55193081/77060264-990f7180-69d8-11ea-9fd8-78deb54433d8.jpg)
![SULD-Work_hour](https://user-images.githubusercontent.com/55193081/77060283-a0cf1600-69d8-11ea-90e2-5e7cb3655c9f.jpg)
![TEJH-work_hours](https://user-images.githubusercontent.com/55193081/77060306-a75d8d80-69d8-11ea-9834-0a2444edb89a.jpg)
![SULD_receiver_filename](https://user-images.githubusercontent.com/55193081/77060327-af1d3200-69d8-11ea-9d49-55eb60f75e35.jpg)
![TEJH_receiver_filename](https://user-images.githubusercontent.com/55193081/77060341-b3e1e600-69d8-11ea-8084-8382e27d5a38.jpg)

**Comment by nho-sdfe** [comment]
Har i samråd med Casper besluttet at sætte SMID og SULD til sende short names i stedet, så det er ligesom TEJH.
Så forsvinder problemer forhåbentlig.

**Comment by nho-sdfe** [comment]
Efter også at have droppet mixed navigation i dag, kom SULD til at virke efter hensigten.
Jeg regner med at SMID også vil køre efter hensigten, når den er blevet oprettet.
