### ISSUE TITLE
Fejl i ADM modul der gør det muligt at reprocesse en station i flere dage.

### ISSUE THREAD

**Issue by casperjepsen** [Kortforsyningen/GORM#3]
Når vi beder om at reprocesse EN station i flere dage så reprocesse den kun den dag der står i TIL feltet. Dvs de dage mellem FRA feltet og indtil til TIL feltet bliver ikke reprocesseret.

**Comment by sjmoller** [comment]
Fejlen er rettet. Installer som root med
```
su - gpsuser -c 'git pull'
~gpsuser/setup/install.sh
systemctl restart jobengine
```

**Comment by kbevers** [comment]
@sjmoller du er for hurtig - vi skal have Tanja med i processen med de her rettelser :-)

**Comment by sjmoller** [comment]
Sorry :-) Prøver at være lidt langsommere...

**Comment by kbevers** [comment]
Tak!

@TanyaPS vil du installere Sørens ændring og lukke det her issue bagefter? Det er ligesom vi gjorde i sidste uge.

**Comment by casperjepsen** [comment]
@TanyaPS Vi skal også have sat jobene over igen for at se om det virker. Hiv endelig fat i mig hvis du har brug for hjælp.
