### ISSUE TITLE
GPSFTP5 genererer 1, 2 og 3 cifrede biblioteksnavne DOY, alle skal være 3 cifrede

### ISSUE THREAD

**Issue by nho-sdfe** [Kortforsyningen/GORM#36]
Genereret fra GPSFTP5
![refgps_rinex3](https://user-images.githubusercontent.com/55193081/97695978-2a81ae80-1aa5-11eb-8fe1-e85b988dd49b.jpg)
Genereret fra GPSFTP4
![refgps_rinex2](https://user-images.githubusercontent.com/55193081/97696321-b3004f00-1aa5-11eb-9b76-0cd7c90b2133.jpg)

**Comment by sjmoller** [comment]
I sbin/ftpuploader, tilføj

         $doy = sprintf("%03d", $doy);
         $hh24 = sprintf("%02d", $hh24);

lige under "# Do the variable substitutions".

/Søren
