### ISSUE TITLE
Reproc af rinex3 data

### ISSUE THREAD

**Issue by casperjepsen** [Kortforsyningen/GORM#4]
Reprocessering af rinex3 data virker, men kun for SBF filer. Hvad når vi skal reprocesssere rinex3 filer der er genereret som rinex3 filer.

**Comment by sjmoller** [comment]
Det forstår jeg ikke helt. Reprocessering burde fungere for alle formater. Det eneste reprocessering gør, er at slette QC tallene fra databasen og flytte alle filer i /data/saved/site/year/doy/* til /data/ftp. Den er helt ligeglad med hvilket format filerne er i.

**Comment by nho-sdfe** [comment]
Efter at have ændret i TEJH headeren i admin modul prøvede jeg at reprocessere dagen i går, altså rinex til rinex processering og det går fint. Ændringerne i headeren slår igennem. Det tager ca. 2 sek. at lave qc på alle 24 1 times filer. Dagsfilen tager ca. 2 min og 40 sek.
