### ISSUE TITLE
Port til (S)FTP forbindelse kan ikke angives i ftpuploader

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/GORM#42]
Behovet for at kunne sende data via FTP/SFTP til en specifik port er opstået. Det er i øjeblikket ikke muligt at angive opsætningen som set herunder.

![gorm](https://user-images.githubusercontent.com/13132571/107036232-93ba4180-67b9-11eb-9c2c-3c5915e76238.jpg)

Quickfixet er at gøre det muligt at angive porten i hostname som på figuren, og så skille dem ad i koden ved indlæsning af konfigurationen. Den mere korrekte måde er at tilføje en ekstra kolonne i `uploaddest` tabellen, udvide admininterface med en ekstra kolonne og diverse kode der læser konfigurationen.

**Comment by sjmoller** [comment]
Jeg har tilføjet kode til at håndtere non-default port numre i hostspecifikationen.
[Patch]https://github.com/Kortforsyningen/GORM/pull/44/commits/d60513b26ccbcf1ab471f085ad05584ed10810c2
