### ISSUE TITLE
Modificer installations scripts sådan at parallelle instanser kan køre samtidigt

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/GORM#6]
Formålet er, at etablere et test-miljø på en maskine som er i produktion. Det skal være muligt at lave en parallel installation i fx `/home/<user>/GORM`. En forudsætning for at det kan lade sig gøre er, at der tilføjes et nyt schema i databasen hvor diverse test directories kan oprettes.

**Comment by sjmoller** [comment]
Jeg er startet på denne aktivitet.
Jeg har brug for at dateret positions patchen installeres først, da der er rettelser i denne jeg skal bruge til dette.
Jeg tænker at løse dette ved at navngive instanser af GORM. Det hele installeres under /usr/local/gorm og lade environment variable styre hvilken konfig Admin og Status CGI + services skal bruge.

**Comment by kbevers** [comment]
> lade environment variable styre hvilken konfig Admin og Status CGI + services skal bruge.

Kan du ikke komme med et eksempel på hvad du mener med det?

**Comment by sjmoller** [comment]
I services har man en setting der hedder "Environment". F.eks ser indeholder ftpuploader.service.
   `Environment="PERL5LIB=/usr/local/lib/gnss"`
Det vil jeg udskifte med
    `Environment="GORMCONF=/usr/local/gorm/etc/gormPROD.conf"`
hvor gormPROD.conf er en YAML fil indeholdende alle paths, environment og andre settings for scriptene. Selve systemd service filen kommer også til at indeholde instansnavnet:
  `ftpuploaderPROD.service`
Det samme gælder CGI scriptene admin.cgi og status.cgi. Her sættes environment variablen i Apache konfig filen for denne instans. Det vil nødvendig også betyde at URL'en for eksempelvis status.cgi også vil komme til at indeholde instansnavnet - http://gpsftp5/PROD/status.cgi

**Comment by kbevers** [comment]
Det lyder som en fin løsning.

**Comment by sjmoller** [comment]
Eller gøre det endnu mere simpelt ved at lave gorm.conf om til en EnvironmentFile, en fil der indeholder initialisering af shell variable. BaseConfig.pm laves om til at initialisere globale kontanter udfra environment variablene sat i gorm.conf. Det gør det også muligt at bruge parametrene i .conf filen direkte (dvs. $ENV{'parameternavn'}....

**Comment by sjmoller** [comment]
Dette er en noget større ændring end jeg havde regnet med.
Jeg kunne derfor godt tænke mig at flytte rundt på det hele sådan at man kan køre en git clone direkte til installations kataloget. Det vil gøre det meget lettere at udvikle på, da man så udvikler direkte på den kørende instans.
Installationen bliver også lettere - f.eks. kunne man skrive:
  cd /usr/local/gorm
  git clone .../GORM.git instanse-name
  cd instanse-name
  ./configure instanse-name
Configure scriptet konfigurerer denne klon ved at installere systemd services og www services samt definere indholdet af gorm.conf parameter filen. Det skal kun gøres een gang i modsætning til nu, hvor scriptene skal installeres hver gang man har lavet en ændring.
Ideen er at man kan have flere kloner kørende parallel på samme host, som hver især kan være forskellige branches. Det gør det også muligt at test-køre en udvikler branch på live data eller parallelle testdata inden man sætter den i prokduktion.
