### ISSUE TITLE
Database: Koordinater skal tidsstyre på samme måde som antenner og modtagere

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/GORM#9]
Det er en fordel hvis koordinaters ændring kan spores over tid.

**Comment by casperjepsen** [comment]
Når der ændres en koordinat på stationen skal den (som nu) indtastes i "Edit Site" i ADM modulet. Dette felt skal gøres tidsstyret på samme vis som Antenne, Modtager og Firmware.

**Comment by sjmoller** [comment]
Dette [rettelse](https://github.com/Kortforsyningen/GORM/commit/fe9597f666f71bd8f62e5d8955e5a5f065b884db) tilføjer netop den funktionalitet.

**Comment by sjmoller** [comment]
Installeret på gpsftp5
